### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by todokku** [TheDrHax/Twitch-Utils#1]
C:\Users\Administrator\Desktop\New folder (6)>twitch_utils record dodgeballcanada -j 2 -b 2M
Checking if channel `dodgeballcanada` is active...
Stream is online! Found the ID of live VOD: 534927868
Starting to record the live stream...
Downloading `https://twitch.tv/dodgeballcanada` into 534927868.end.ts
Process Process-1:
Traceback (most recent call last):
  File "e:\users\administrator\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\users\administrator\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "e:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\twitch_utils\record.py", line 57, in download
    sl_proc = Popen(sl_cmd, **sl_kwargs)
  File "e:\users\administrator\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "e:\users\administrator\appdata\local\programs\python\python36\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "e:\users\administrator\appdata\local\programs\python\python36\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable

**Comment by TheDrHax** [comment]
This should fix it. However I'm not sure about `-b` flag on Windows. It may work if you have `pv` utility, but I haven't tested it yet.
